# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from streams.private.v1 import streams_service_pb2 as streams_dot_private_dot_v1_dot_streams__service__pb2


class StreamsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/cloud.api.streams.private.v1.StreamsService/Get',
        request_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.SerializeToString,
        response_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.FromString,
        )
    self.Publish = channel.unary_unary(
        '/cloud.api.streams.private.v1.StreamsService/Publish',
        request_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.SerializeToString,
        response_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.FromString,
        )
    self.PublishDone = channel.unary_unary(
        '/cloud.api.streams.private.v1.StreamsService/PublishDone',
        request_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.SerializeToString,
        response_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.FromString,
        )
    self.Run = channel.unary_unary(
        '/cloud.api.streams.private.v1.StreamsService/Run',
        request_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.SerializeToString,
        response_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.FromString,
        )
    self.Stop = channel.unary_unary(
        '/cloud.api.streams.private.v1.StreamsService/Stop',
        request_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.SerializeToString,
        response_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.FromString,
        )


class StreamsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Publish(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishDone(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Run(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Stop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StreamsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.FromString,
          response_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.SerializeToString,
      ),
      'Publish': grpc.unary_unary_rpc_method_handler(
          servicer.Publish,
          request_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.FromString,
          response_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.SerializeToString,
      ),
      'PublishDone': grpc.unary_unary_rpc_method_handler(
          servicer.PublishDone,
          request_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.FromString,
          response_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.SerializeToString,
      ),
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.FromString,
          response_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.SerializeToString,
      ),
      'Stop': grpc.unary_unary_rpc_method_handler(
          servicer.Stop,
          request_deserializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamRequest.FromString,
          response_serializer=streams_dot_private_dot_v1_dot_streams__service__pb2.StreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cloud.api.streams.private.v1.StreamsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
