// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: servicemanager/v1/resources.proto

package v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The full representation of a Service that is managed by
// VideoCoin management.
type ManagedService struct {
	// The name of the service. For example: `symphony.videocoin.network`.
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagedService) Reset()         { *m = ManagedService{} }
func (m *ManagedService) String() string { return proto.CompactTextString(m) }
func (*ManagedService) ProtoMessage()    {}
func (*ManagedService) Descriptor() ([]byte, []int) {
	return fileDescriptor_b741947ec5fef124, []int{0}
}
func (m *ManagedService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedService.Unmarshal(m, b)
}
func (m *ManagedService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedService.Marshal(b, m, deterministic)
}
func (m *ManagedService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedService.Merge(m, src)
}
func (m *ManagedService) XXX_Size() int {
	return xxx_messageInfo_ManagedService.Size(m)
}
func (m *ManagedService) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedService.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedService proto.InternalMessageInfo

func (m *ManagedService) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (*ManagedService) XXX_MessageName() string {
	return "cloud.api.servicemanager.v1.ManagedService"
}
func init() {
	proto.RegisterType((*ManagedService)(nil), "cloud.api.servicemanager.v1.ManagedService")
	golang_proto.RegisterType((*ManagedService)(nil), "cloud.api.servicemanager.v1.ManagedService")
}

func init() { proto.RegisterFile("servicemanager/v1/resources.proto", fileDescriptor_b741947ec5fef124) }
func init() {
	golang_proto.RegisterFile("servicemanager/v1/resources.proto", fileDescriptor_b741947ec5fef124)
}

var fileDescriptor_b741947ec5fef124 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xcd, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0xd2, 0x2f, 0x33, 0xd4, 0x2f, 0x4a,
	0x2d, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4e,
	0xce, 0xc9, 0x2f, 0x4d, 0xd1, 0x4b, 0x2c, 0xc8, 0xd4, 0x43, 0x55, 0xac, 0x57, 0x66, 0x28, 0xa5,
	0x9b, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9e, 0x9f, 0x9e, 0xaf,
	0x0f, 0xd6, 0x93, 0x54, 0x9a, 0x06, 0xe6, 0x81, 0x39, 0x60, 0x16, 0xc4, 0x2c, 0x25, 0x63, 0x2e,
	0x3e, 0x5f, 0xb0, 0xe6, 0x94, 0x60, 0x88, 0x51, 0x42, 0x8a, 0x5c, 0x3c, 0x50, 0x53, 0xe3, 0xf3,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xb8, 0xa1, 0x62, 0x7e, 0x89, 0xb9,
	0xa9, 0x4e, 0x12, 0x27, 0x1e, 0xc9, 0x31, 0x5c, 0x78, 0x24, 0xc7, 0xf0, 0xe0, 0x91, 0x1c, 0xc3,
	0x81, 0xc7, 0x72, 0x8c, 0x27, 0x1e, 0xcb, 0x31, 0x46, 0x31, 0x95, 0x19, 0x26, 0xb1, 0x81, 0x4d,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x28, 0x7d, 0xe4, 0x78, 0xc6, 0x00, 0x00, 0x00,
}
