// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: billing/private/v1/billing_service.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	v1 "github.com/videocoin/cloud-api/billing/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProfileRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileRequest) Reset()         { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()    {}
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55404a463757807e, []int{0}
}
func (m *ProfileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRequest.Merge(m, src)
}
func (m *ProfileRequest) XXX_Size() int {
	return m.Size()
}
func (m *ProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRequest proto.InternalMessageInfo

func (m *ProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (*ProfileRequest) XXX_MessageName() string {
	return "cloud.api.billing.private.v1.ProfileRequest"
}

type ChargesRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargesRequest) Reset()         { *m = ChargesRequest{} }
func (m *ChargesRequest) String() string { return proto.CompactTextString(m) }
func (*ChargesRequest) ProtoMessage()    {}
func (*ChargesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55404a463757807e, []int{1}
}
func (m *ChargesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChargesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChargesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChargesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargesRequest.Merge(m, src)
}
func (m *ChargesRequest) XXX_Size() int {
	return m.Size()
}
func (m *ChargesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChargesRequest proto.InternalMessageInfo

func (m *ChargesRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (*ChargesRequest) XXX_MessageName() string {
	return "cloud.api.billing.private.v1.ChargesRequest"
}
func init() {
	proto.RegisterType((*ProfileRequest)(nil), "cloud.api.billing.private.v1.ProfileRequest")
	golang_proto.RegisterType((*ProfileRequest)(nil), "cloud.api.billing.private.v1.ProfileRequest")
	proto.RegisterType((*ChargesRequest)(nil), "cloud.api.billing.private.v1.ChargesRequest")
	golang_proto.RegisterType((*ChargesRequest)(nil), "cloud.api.billing.private.v1.ChargesRequest")
}

func init() {
	proto.RegisterFile("billing/private/v1/billing_service.proto", fileDescriptor_55404a463757807e)
}
func init() {
	golang_proto.RegisterFile("billing/private/v1/billing_service.proto", fileDescriptor_55404a463757807e)
}

var fileDescriptor_55404a463757807e = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x8d, 0x87, 0x89, 0x39, 0xec, 0x90, 0xd3, 0x28, 0x52, 0x65, 0x22, 0xec, 0xe0, 0x12,
	0xaa, 0x78, 0x16, 0xaa, 0x30, 0x76, 0x93, 0x89, 0x17, 0x2f, 0xa3, 0x7f, 0xde, 0x75, 0x2f, 0xd6,
	0xa6, 0x26, 0x69, 0xc0, 0x6f, 0xe7, 0x71, 0x47, 0x3f, 0x81, 0x48, 0xf7, 0x45, 0x64, 0x69, 0x27,
	0x1b, 0x38, 0xc5, 0x5b, 0xdf, 0xe6, 0xf9, 0xe5, 0xf9, 0xe5, 0xa5, 0x83, 0x18, 0xf3, 0x1c, 0x8b,
	0x4c, 0x94, 0x0a, 0x6d, 0x64, 0x40, 0xd8, 0x40, 0xb4, 0xbf, 0xa6, 0x1a, 0x94, 0xc5, 0x04, 0x78,
	0xa9, 0xa4, 0x91, 0xec, 0x28, 0xc9, 0x65, 0x95, 0xf2, 0xa8, 0x44, 0xde, 0x06, 0x78, 0xcb, 0x70,
	0x1b, 0x78, 0xc3, 0x0c, 0xcd, 0xbc, 0x8a, 0x79, 0x22, 0x9f, 0x45, 0x26, 0x33, 0x29, 0x1c, 0x14,
	0x57, 0x33, 0x37, 0xb9, 0xc1, 0x7d, 0x35, 0x97, 0x79, 0xd7, 0x1b, 0x71, 0x8b, 0x29, 0xc8, 0x44,
	0x62, 0x21, 0x5c, 0xc3, 0x30, 0x2a, 0x71, 0xad, 0xb0, 0xd3, 0xa6, 0x7f, 0x45, 0xbb, 0x77, 0x4a,
	0xce, 0x30, 0x87, 0x09, 0xbc, 0x54, 0xa0, 0x0d, 0x3b, 0xa5, 0x07, 0x95, 0x06, 0x35, 0xc5, 0xb4,
	0x47, 0x4e, 0xc8, 0xe0, 0x30, 0xa4, 0xf5, 0xc7, 0x71, 0xe7, 0x41, 0x83, 0x1a, 0xdf, 0x4e, 0x3a,
	0xab, 0xa3, 0x71, 0xba, 0xc2, 0x6e, 0xe6, 0x91, 0xca, 0x40, 0xff, 0x07, 0xbb, 0xa8, 0x09, 0xed,
	0x86, 0x8d, 0xc7, 0x7d, 0xa3, 0xc1, 0x9e, 0x28, 0x1b, 0x81, 0x69, 0x1d, 0xc2, 0xd7, 0x06, 0x60,
	0xe7, 0xfc, 0xb7, 0x2d, 0xf1, 0x6d, 0x65, 0xef, 0xec, 0x87, 0xf4, 0x66, 0x4a, 0x97, 0xb2, 0xd0,
	0xd0, 0xdf, 0x63, 0x09, 0xa5, 0x23, 0x30, 0xad, 0xf9, 0x5f, 0x25, 0xdb, 0x0f, 0xdc, 0x55, 0xf2,
	0x9d, 0x5a, 0x97, 0x84, 0xbd, 0x45, 0xed, 0x93, 0xf7, 0xda, 0x27, 0x9f, 0xb5, 0x4f, 0xde, 0x96,
	0x3e, 0x59, 0x2c, 0x7d, 0xf2, 0xb8, 0x6f, 0x83, 0xb8, 0xe3, 0x76, 0x7e, 0xf9, 0x15, 0x00, 0x00,
	0xff, 0xff, 0xfd, 0x75, 0x1c, 0x34, 0x2d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BillingServiceClient interface {
	GetProfileByUserID(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*v1.ProfileResponse, error)
	GetCharges(ctx context.Context, in *ChargesRequest, opts ...grpc.CallOption) (*v1.ChargesResponse, error)
}

type billingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBillingServiceClient(cc *grpc.ClientConn) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetProfileByUserID(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*v1.ProfileResponse, error) {
	out := new(v1.ProfileResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.billing.private.v1.BillingService/GetProfileByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetCharges(ctx context.Context, in *ChargesRequest, opts ...grpc.CallOption) (*v1.ChargesResponse, error) {
	out := new(v1.ChargesResponse)
	err := c.cc.Invoke(ctx, "/cloud.api.billing.private.v1.BillingService/GetCharges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
type BillingServiceServer interface {
	GetProfileByUserID(context.Context, *ProfileRequest) (*v1.ProfileResponse, error)
	GetCharges(context.Context, *ChargesRequest) (*v1.ChargesResponse, error)
}

// UnimplementedBillingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBillingServiceServer struct {
}

func (*UnimplementedBillingServiceServer) GetProfileByUserID(ctx context.Context, req *ProfileRequest) (*v1.ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileByUserID not implemented")
}
func (*UnimplementedBillingServiceServer) GetCharges(ctx context.Context, req *ChargesRequest) (*v1.ChargesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCharges not implemented")
}

func RegisterBillingServiceServer(s *grpc.Server, srv BillingServiceServer) {
	s.RegisterService(&_BillingService_serviceDesc, srv)
}

func _BillingService_GetProfileByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetProfileByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.billing.private.v1.BillingService/GetProfileByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetProfileByUserID(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetCharges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetCharges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.api.billing.private.v1.BillingService/GetCharges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetCharges(ctx, req.(*ChargesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BillingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.api.billing.private.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfileByUserID",
			Handler:    _BillingService_GetProfileByUserID_Handler,
		},
		{
			MethodName: "GetCharges",
			Handler:    _BillingService_GetCharges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/private/v1/billing_service.proto",
}

func (m *ProfileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.UserID) > 0 {
		i -= len(m.UserID)
		copy(dAtA[i:], m.UserID)
		i = encodeVarintBillingService(dAtA, i, uint64(len(m.UserID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChargesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChargesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChargesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.UserID) > 0 {
		i -= len(m.UserID)
		copy(dAtA[i:], m.UserID)
		i = encodeVarintBillingService(dAtA, i, uint64(len(m.UserID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBillingService(dAtA []byte, offset int, v uint64) int {
	offset -= sovBillingService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProfileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserID)
	if l > 0 {
		n += 1 + l + sovBillingService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ChargesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserID)
	if l > 0 {
		n += 1 + l + sovBillingService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBillingService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBillingService(x uint64) (n int) {
	return sovBillingService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProfileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBillingService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBillingService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBillingService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBillingService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBillingService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBillingService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChargesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBillingService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChargesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChargesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBillingService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBillingService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBillingService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBillingService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBillingService
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBillingService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBillingService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBillingService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBillingService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBillingService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBillingService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBillingService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBillingService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBillingService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBillingService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBillingService = fmt.Errorf("proto: unexpected end of group")
)
